server:
  port: 8081

spring:
  cloud:
    consul:
      discovery:
        tags: app, authorization
        healthCheckPath: /actuator/health
        healthCheckInterval: 30s
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER_NAME}
    password: ${MYSQL_USER_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
